# Generated by Django 4.1.7 on 2023-03-30 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveBigIntegerField()),
                ("amount", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
                ("zip_from", models.CharField(max_length=10)),
                ("zip_to", models.CharField(max_length=10)),
            ],
        ),
    ]
