# Generated by Django 4.1.7 on 2023-03-31 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="height",
            field=models.PositiveIntegerField(verbose_name="Height (cm)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Lenght in (cm)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.PositiveBigIntegerField(verbose_name="Order number"),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight",
            field=models.FloatField(verbose_name="Weight (kg)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="width",
            field=models.PositiveIntegerField(verbose_name="Width (cm)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_from",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "[0-9]+$", "Enter a valid zip code."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_to",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "[0-9]+$", "Enter a valid zip code."
                    )
                ],
            ),
        ),
    ]
